version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: fincoach_db
      POSTGRES_USER: fincoach
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fincoach -d fincoach_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fincoach:password@db:5432/fincoach_db
      JWT_SECRET_KEY: dev-secret-key-change-in-production
      DEBUG: "true"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./models:/app/models
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8000/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add a frontend service when ready
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   environment:
  #     REACT_APP_API_URL: http://localhost:8000
  #   depends_on:
  #     - backend

volumes:
  postgres_data:

networks:
  default:
    name: fincoach-network
